apiVersion: backstage.io/v1alpha1
kind: Resource

metadata:
  name: s3-bucket-delete-workflow-test

  description: "AWS S3 provisioned through Harness IDP."

  tags:
    - AWS
    - S3
    - Development

  annotations:
    backstage.io/techdocs-ref: dir:.

    company.com/cost-center: "CC-1020"

    company.com/catalog-file: "S3-s3-bucket-delete-workflow-test.yaml"
    company.com/workspace-name: "s3-bucket-delete-workflow-test"
    company.com/cloud-provider: "AWS"
    company.com/resource-type: "S3"
    company.com/environment: "Development"
    company.com/owner: "Anish"

  links:
    - title: Update Infrastructure
      url: "/create/templates/default/update-infrastructure-template?resource_name=<resource_name>&resource_type=<resource_type>&cloud_provider=<cloud_provider>"
      icon: update

    - title: Delete Infrastructure
      url: "/create/templates/default/delete-infrastructure-template"
      icon: delete

spec:
  type: infrastructure
  lifecycle: Development
  owner: Anish
